# Generated by Django 3.0.8 on 2020-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zipcode',
            field=models.IntegerField(default=94102),
            preserve_default=False,
        ),
    ]
