# Generated by Django 3.0.8 on 2020-07-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
