# Generated by Django 3.0.8 on 2020-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200714_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
